version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: amo_app_dev
    working_dir: /app
    user: root:${GID:-1028}
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/app
    ports:
      - 1500:80
    links:
      - mongo
    command: bash -c "php -S 0.0.0.0:80 -t ./public"

  mongo:
    image: mongo:4.4.23
    container_name: amo_mongo_dev
    environment:
      - 'TZ=Europe/Moscow'
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    restart: always
    ports:
      - '27019:27017'
    volumes:
      - ./data:/data/db
