version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: amo_app_dev
    working_dir: /app
    user: root:${GID:-1028}
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/app
    ports:
      - 1500:80
    command: bash -c "php -S 0.0.0.0:80 -t ./public"
